name: 'Set Action Secret'

author: Habid Manzur

description: 'Create or update secrets in github repository'

branding:
  icon: lock
  color: gray-dark

inputs:
  name:
    description: Secret name
    required: true

  value:
    description: Secret value
    required: true

  repository:
    description: Repository name
    default: false
    required: false

  owner:
    description: Owner of repository
    default: false
    required: false

  push_to_org:
    description: Flag to use organization endpoint for secret
    default: false
    required: false

  token:
    description: Repository access token
    required: true

runs:
  using: 'node12'
  main: 'secret.js'